# Generated by Django 4.1 on 2024-07-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_type', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('state', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('college', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('school', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('year_of_study', models.CharField(default='', max_length=20)),
                ('representative_type', models.CharField(choices=[('college', 'College'), ('school', 'School')], default='college', max_length=10)),
                ('unique_id', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('name', 'state', 'district')},
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('name', 'state', 'district')},
            },
        ),
        migrations.CreateModel(
            name='CollegeRepresentative',
            fields=[
            ],
            options={
                'verbose_name': 'College Representative',
                'verbose_name_plural': 'College Representatives',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.userprofile',),
        ),
        migrations.CreateModel(
            name='SchoolRepresentative',
            fields=[
            ],
            options={
                'verbose_name': 'School Representative',
                'verbose_name_plural': 'School Representatives',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.userprofile',),
        ),
    ]
