# Generated by Django 5.0.7 on 2024-07-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unique_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
